"""Telegram configuration, authorization, and publication contracts."""

from prism_core.telegram.auth import TelegramAuthorizationError, TelegramAuthorizer
from prism_core.telegram.config import TelegramConfig
from prism_core.telegram.publisher import (
    AuditStatus,
    FakeTelegramTransport,
    InMemoryFixedWindowRateLimiter,
    InMemoryTelegramAuditSink,
    InMemoryTelegramDedupeStore,
    PublicationOutcomeUnknown,
    PublicationRejected,
    PublicationResult,
    PublicationStatus,
    PublicationValidationError,
    StdlibTelegramBotApiRequester,
    TelegramAuditRecord,
    TelegramAuditSink,
    TelegramBotApiTransport,
    TelegramBotApiRequester,
    TelegramDedupeStore,
    TelegramPublisher,
    TelegramRateLimiter,
    TelegramTransport,
    TelegramTransportError,
)

__all__ = [
    "AuditStatus",
    "FakeTelegramTransport",
    "InMemoryFixedWindowRateLimiter",
    "InMemoryTelegramAuditSink",
    "InMemoryTelegramDedupeStore",
    "PublicationOutcomeUnknown",
    "PublicationRejected",
    "PublicationResult",
    "PublicationStatus",
    "PublicationValidationError",
    "StdlibTelegramBotApiRequester",
    "TelegramAuditRecord",
    "TelegramAuditSink",
    "TelegramAuthorizationError",
    "TelegramAuthorizer",
    "TelegramBotApiTransport",
    "TelegramBotApiRequester",
    "TelegramConfig",
    "TelegramDedupeStore",
    "TelegramPublisher",
    "TelegramRateLimiter",
    "TelegramTransport",
    "TelegramTransportError",
]
